### ISSUE TITLE
Sync with vscode after sign in

### ISSUE THREAD

**Issue by TiyaniMilton** [Cha0s2nd/cha0s2nd-vscode-cds#10]
It popup the d365 sign-in screen after like 5-10 minutes then after successful sign-in it does nothing

**Comment by Cha0s2nd** [comment]
Hi, could you check that you're not getting popup blocked by the browser? It should open vscode and ask you to allow it to be open by an external application.

**Comment by Cha0s2nd** [comment]
Added the ability to manually enter the authorization code after login to get around browser popup blocks and url pop blocks in vscode.
